
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 02 14:48:57 CST 2012
//----------------------------------------------------

package PTSintax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 13;
  public static final int DOSPUNTOS = 8;
  public static final int STARTFN = 44;
  public static final int FUNCTION = 48;
  public static final int MENOSMENOS = 14;
  public static final int MULT = 11;
  public static final int CASE = 39;
  public static final int PRINTFN = 40;
  public static final int MAYQ = 16;
  public static final int INT = 36;
  public static final int FOR = 29;
  public static final int CORCHDERECH = 6;
  public static final int AND = 51;
  public static final int NOT = 22;
  public static final int MENQ = 17;
  public static final int OR = 23;
  public static final int BOOL = 50;
  public static final int MENIGU = 19;
  public static final int CORCHIZQUI = 7;
  public static final int DIV = 12;
  public static final int BEGIN = 32;
  public static final int FLOTANTES = 26;
  public static final int IF = 27;
  public static final int ID = 52;
  public static final int IGU = 20;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int ASIG = 15;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int CADENA = 53;
  public static final int DIF = 21;
  public static final int ENTEROS = 25;
  public static final int READLN = 45;
  public static final int PIZQUIERDO = 5;
  public static final int SWITCH = 49;
  public static final int PCOMA = 2;
  public static final int REST = 10;
  public static final int BOLEANOS = 24;
  public static final int ELSE = 28;
  public static final int PUNTO = 43;
  public static final int TO = 34;
  public static final int WHILE = 31;
  public static final int DEFAULT = 47;
  public static final int LET = 41;
  public static final int FLOAT = 38;
  public static final int THEN = 46;
  public static final int PDERECHO = 4;
  public static final int END = 33;
  public static final int SUM = 9;
  public static final int STRING = 37;
  public static final int DOWNTO = 35;
  public static final int DO = 30;
  public static final int MAYIGU = 18;
}

